### PR TITLE
Add mysql-admin interface to layer-index

### PR DESCRIPTION
**Pull request by davigar15**
This interface the same as the mysql interface, but additionally it provides the password of the root user.

### CODE REVIEW

**Comment by davigar15** [comment]
A charm from the kubeflow bundle is currently using this layer, and @knkski asked me to have it in the layer index.

**Comment by kwmonroe** [comment]
@davigar15 i'm curious -- what's the difference between this `mysql-admin` interface and [mysql-root](https://github.com/juju-solutions/interface-mysql-root)?  The latter is already in this index.

**Comment by davigar15** [comment]
`mysql` interface provides the user connection data for a standard user
`mysql-root` does the same, but for a user with privilege rights.

The interface I'm proposing it provides the credentials for the root user and an standard user. (both)

**Comment by johnsca** [comment]
The naming of these interfaces seems backward according to that description (i.e., I would expect `mysql-root` to provide the root user credentials, while `mysql-admin` would provide a non-root, admin-level user), but either way, the description of the interface in the PR is identical to the one already there for `mysql-root`, so at least one of them should be changed so that it's clear what the difference is.

**Comment by davigar15** [comment]
Any update @kwmonroe?

**Review by johnsca — APPROVED** [review]

**Pull request merged**
