### PR TITLE
Osm ns

### PR DESCRIPTION
**Pull request by AdamIsrael**
Please make sure you do the following when updating the layer index:

* [X] Add or update the JSON file for your layer, in the appropriate subdirectory (`layers` or `interfaces`)
* [ ] Add an explicit `docs` URL field to your JSON, if appropriate.  If omitted, it will default to the `README.md` at the root of your repo, but you may want to provide a more specific URL.  If you're using the `subdir` field, then you definitely want to point to the README of the layer rather than the repo.
* [X] Run `update_readme.py` to update the user-friendly index in the README

### CODE REVIEW

**Comment by hyperbolic2346** [comment]
@AdamIsrael Just making sure you know you added the mongo stuff in here.

**Comment by AdamIsrael** [comment]
Good catch, @hyperbolic2346. I didn't mean to include the mongodb interface. I've updated the PR to reflect that.

**Comment by hyperbolic2346** [comment]
@AdamIsrael did you mean to nuke the original cloud-green one?

**Comment by AdamIsrael** [comment]
Hey @hyperbolic2346. I didn't mean to pull the cloud-green version *yet*, but I did find in earlier testing that the interface isn't functional and hasn't been supported in a while. At the time, I think we checked and found that it hadn't been pulled in a while.

I fixed this pull request (again, mea culpa) and I'll open an issue about the cloud-green version and assign it to myself. We've made an improved version of the mongodb interface but I want to finish testing before I make that available.

**Comment by hyperbolic2346** [comment]
Sorry, @AdamIsrael. I feel like I keep poking you on this, but I'll need you to run update_readme.py again so the mongo stuff gets put back into the index.

**Comment by AdamIsrael** [comment]
@hyperbolic2346 Totally my fault for that, sorry. Updated, again!

**Comment by AdamIsrael** [comment]
Okay, I double-checked for real this time and I think this is correct. Two files changed, and mongodb is intact in the README.

**Comment by hyperbolic2346** [comment]
Thanks for fighting through this one! We made it in the end. :)

**Pull request merged**
